require 'lsp.config'
require 'lsp.installer'

require 'conf.colorscheme.edge'
require 'conf.colorscheme.sonokai'
require 'conf.colorscheme.gruvbox'

require 'conf.mason'
require 'conf.bubbly'
require 'conf.harpoon'
require 'conf.undotree'
require 'conf.vim-fuzzy-stash'
require 'conf.nvim-surround'
require 'conf.vim-bookmarks'
require 'conf.nvim-notify'
require 'conf.hop'
require 'conf.tmux-send'
require 'conf.nvim-colorizer'
require 'conf.vim-simple-align'
require 'conf.targets'
require 'conf.vim-svelte-plugin'
require 'conf.vimux'
require 'conf.vim-rest-console'
require 'conf.switch'
require 'conf.treesitter'
-- require 'conf.lazygit'
require 'conf.fugitive'
require 'conf.git-blame'
-- require 'conf.gitsigns'
require 'conf.todo-txt'
require 'conf.nvim-tree'
require 'conf.caw'
require 'conf.todo-comments'
require 'conf.trouble'
require 'conf.neoclip'
require 'conf.cmp'
require 'conf.luasnip'
require 'conf.telescope'
