require 'lsp.config'

require 'conf.colorscheme.edge'
require 'conf.colorscheme.sonokai'
require 'conf.colorscheme.gruvbox'

require 'conf.caw'
require 'conf.cmp'
require 'conf.fugitive'
require 'conf.git-blame'
require 'conf.gitsigns'
require 'conf.harpoon'
require 'conf.headlines'
require 'conf.hop'
-- require 'conf.indent-blankline'
-- require 'conf.lazygit'
require 'conf.luasnip'
require 'conf.mason'
require 'conf.mason-lspconfig'
require 'conf.neoclip'
require 'conf.neodev'
require 'conf.nvim-colorizer'
require 'conf.nvim-surround'
require 'conf.nvim-tree' require 'conf.nvim-treesitter-context'
require 'conf.nvim-ufo'
-- require 'conf.replacer'
require 'conf.switch'
require 'conf.targets'
require 'conf.telescope'
require 'conf.tmux-send'
require 'conf.todo-comments'
require 'conf.todo-txt'
require 'conf.treesitter'
require 'conf.trouble'
require 'conf.undotree'
require 'conf.vim-bookmarks'
require 'conf.vim-fuzzy-stash'
require 'conf.vim-rest-console'
require 'conf.vim-simple-align'
require 'conf.vim-svelte-plugin'
require 'conf.vimux'

require 'conf.windline'
require 'conf.dap'
